### ISSUE TITLE
To add to recipe

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/checklist-recipe#9]
- Note about encoding
- Loaded packages should be installed first

**Comment by damianooldoni** [comment]
- Note about encoding: not added because issue about UTF-8 for WIndows pc is still not solved and for OSX users is not needed
- Installation packages: instructions added, see c60c2440a67a48038c93ffaceb193ecbf73144f3

Further Markdown cleaning in a2fd7b4e9d5b700c841c04679ff688b3b73e56ae

For further add-ins in recipe, just let me know.

**Comment by peterdesmet** [comment]
Loading packages is now part of https://github.com/trias-project/checklist-recipe/wiki/Getting-started#run-code
